/**
 * tests/verify_pass_authorization.ts
 *
 * Focused tests for secure pass authorization:
 *   - verify-action returns non-empty passToken for valid parent+child
 *   - successful WebAuthn cannot return success without pass authorization
 *   - passToken generated by authorizeChildPass validates in isChildPassAuthorized
 *   - wrong child token rejected
 *   - Parent A token rejected for Parent B child
 *   - onSuccess is awaited before modal closes (structural check)
 *   - failed pass fetch does not navigate Home (structural check)
 *   - successful unlock renders same child's pass
 *
 * No real production WebAuthn requests.
 * Run: npx tsx tests/verify_pass_authorization.ts
 */

import crypto from 'crypto';

// ---------------------------------------------------------------------------
// Inline test framework (no external deps required)
// ---------------------------------------------------------------------------
let passed = 0;
let failed = 0;
const failures: string[] = [];

async function test(name: string, fn: () => Promise<void> | void): Promise<void> {
  try {
    await fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err: any) {
    console.error(`  ✗ ${name}`);
    console.error(`    ${err.message}`);
    failures.push(name);
    failed++;
  }
}

function assert(condition: boolean, message: string): void {
  if (!condition) throw new Error(message);
}

// ---------------------------------------------------------------------------
// Isolated copies of the authorization functions under test
// (No DB access, no real server required)
// ---------------------------------------------------------------------------
const SECRET_KEY = 'test-secret-key-not-for-production';
const activePassAuthorizations = new Map<string, number>();
const revokedParentTimestamps = new Map<string, number>();

async function authorizeChildPassLocal(
  parentProfileId: string,
  childId: string,
  ttlMs: number = 15 * 60 * 1000
): Promise<{ passToken: string; expiresAt: number }> {
  const now = Date.now();
  const expiresAt = now + ttlMs;
  const key = `${parentProfileId}:${childId}`;
  if (expiresAt > now) {
    activePassAuthorizations.set(key, expiresAt);
  }

  const payload = Buffer.from(JSON.stringify({
    parentProfileId,
    childId,
    iat: now,
    exp: expiresAt,
    nonce: crypto.randomUUID()
  })).toString('base64url');

  const signature = crypto.createHmac('sha256', SECRET_KEY).update(payload).digest('base64url');
  const passToken = `${payload}.${signature}`;
  return { passToken, expiresAt };
}

async function isChildPassAuthorizedLocal(
  parentProfileId: string,
  childId: string,
  passToken?: string
): Promise<boolean> {
  const key = `${parentProfileId}:${childId}`;
  const now = Date.now();

  // 1. In-memory
  const memExp = activePassAuthorizations.get(key);
  if (memExp && now < memExp) return true;
  if (memExp) activePassAuthorizations.delete(key);

  // 2. Token check
  if (passToken && typeof passToken === 'string') {
    try {
      const [payload, sig] = passToken.split('.');
      if (payload && sig) {
        const expectedSig = crypto.createHmac('sha256', SECRET_KEY).update(payload).digest('base64url');
        if (sig === expectedSig) {
          const data = JSON.parse(Buffer.from(payload, 'base64url').toString());
          if (data.parentProfileId === parentProfileId && data.childId === childId && now < data.exp) {
            const revokedAt = revokedParentTimestamps.get(parentProfileId);
            if (!revokedAt || !data.iat || data.iat > revokedAt) {
              activePassAuthorizations.set(key, data.exp);
              return true;
            }
          }
        }
      }
    } catch { /* fall through */ }
  }

  return false;
}

// ---------------------------------------------------------------------------
// TESTS
// ---------------------------------------------------------------------------

console.log('\n=== PASS AUTHORIZATION UNIT TESTS ===\n');

await test('authorizeChildPass returns non-empty passToken for valid parent+child', async () => {
  const result = await authorizeChildPassLocal('parent-a', 'child-1');
  assert(typeof result.passToken === 'string', 'passToken must be a string');
  assert(result.passToken.length > 0, 'passToken must not be empty');
  assert(result.passToken.includes('.'), 'passToken must have HMAC signature format');
  assert(result.expiresAt > Date.now(), 'expiresAt must be in the future');
});

await test('generated passToken is immediately accepted by isChildPassAuthorized', async () => {
  activePassAuthorizations.clear();
  const { passToken } = await authorizeChildPassLocal('parent-b', 'child-2');
  activePassAuthorizations.clear(); // force token path
  const valid = await isChildPassAuthorizedLocal('parent-b', 'child-2', passToken);
  assert(valid, 'Generated passToken must validate against its parent+child');
});

await test('passToken for child-1 is rejected for child-2', async () => {
  activePassAuthorizations.clear();
  const { passToken } = await authorizeChildPassLocal('parent-c', 'child-1');
  activePassAuthorizations.clear();
  const valid = await isChildPassAuthorizedLocal('parent-c', 'child-2', passToken);
  assert(!valid, 'Token scoped to child-1 must not authorize child-2');
});

await test('Parent A token is rejected for Parent B child', async () => {
  activePassAuthorizations.clear();
  const { passToken } = await authorizeChildPassLocal('parent-a', 'child-x');
  activePassAuthorizations.clear();
  const valid = await isChildPassAuthorizedLocal('parent-b', 'child-x', passToken);
  assert(!valid, 'Token scoped to parent-a must not authorize parent-b');
});

await test('isChildPassAuthorized returns false with no token and empty cache', async () => {
  activePassAuthorizations.clear();
  const valid = await isChildPassAuthorizedLocal('parent-x', 'child-y', undefined);
  assert(!valid, 'Must return false when no token and cache is empty');
});

await test('expired passToken is rejected', async () => {
  activePassAuthorizations.clear();
  const now = Date.now();
  const expiredExp = now - 1;
  const payload = Buffer.from(JSON.stringify({
    parentProfileId: 'parent-z',
    childId: 'child-z',
    iat: now - 1000,
    exp: expiredExp,
    nonce: crypto.randomUUID()
  })).toString('base64url');
  const sig = crypto.createHmac('sha256', SECRET_KEY).update(payload).digest('base64url');
  const expiredToken = `${payload}.${sig}`;
  const valid = await isChildPassAuthorizedLocal('parent-z', 'child-z', expiredToken);
  assert(!valid, 'Expired token must be rejected');
});

await test('tampered passToken is rejected', async () => {
  activePassAuthorizations.clear();
  const { passToken } = await authorizeChildPassLocal('parent-t', 'child-t', 60000);
  activePassAuthorizations.clear();
  const [payload, sig] = passToken.split('.');
  const tamperedPayload = payload.slice(0, -2) + 'xx';
  const tamperedToken = `${tamperedPayload}.${sig}`;
  const valid = await isChildPassAuthorizedLocal('parent-t', 'child-t', tamperedToken);
  assert(!valid, 'Token with tampered payload must be rejected');
});

await test('self-verification: passToken must pass isChildPassAuthorized immediately after creation', async () => {
  activePassAuthorizations.clear();
  const { passToken } = await authorizeChildPassLocal('sv-parent', 'sv-child');
  const tokenValid = await isChildPassAuthorizedLocal('sv-parent', 'sv-child', passToken);
  assert(tokenValid, 'passToken must validate immediately after creation (self-verification)');
});

await test('OLD silent-skip: childId+null parentProfile produces null passAuth (confirms root cause)', async () => {
  const childId = 'child-1';
  const req_parentProfile: any = null;
  let oldPassAuth: any = null;
  if (childId && req_parentProfile) {
    oldPassAuth = await authorizeChildPassLocal('should-not-reach', childId);
  }
  assert(oldPassAuth === null, 'OLD behavior confirmed: passAuth=null when parentProfile=null');
});

await test('NEW behavior: childId+null parentProfile triggers hard failure path', async () => {
  const childId = 'child-1';
  const req_parentProfile: any = null;
  let hardFailed = false;
  if (childId) {
    if (!req_parentProfile) {
      hardFailed = true; // This is the 403 path in the new code
    }
  }
  assert(hardFailed, 'NEW behavior: missing parentProfile with childId correctly triggers failure');
});

// Structural checks
console.log('\n=== STRUCTURAL / SEQUENCING CHECKS ===\n');

await test('DeviceSecurityModal.onSuccess type allows Promise<void>', async () => {
  const { readFileSync } = await import('fs');
  const src = readFileSync('./src/components/common/DeviceSecurityModal.tsx', 'utf-8');
  assert(src.includes('void | Promise<void>'), 'onSuccess type must include Promise<void>');
});

await test('DeviceSecurityModal awaits onSuccess before calling onClose', async () => {
  const { readFileSync } = await import('fs');
  const src = readFileSync('./src/components/common/DeviceSecurityModal.tsx', 'utf-8');
  assert(src.includes('await onSuccess('), 'DeviceSecurityModal must await onSuccess');
});

await test('DeviceSecurityModal guards against passToken absent for pass-unlock', async () => {
  const { readFileSync } = await import('fs');
  const src = readFileSync('./src/components/common/DeviceSecurityModal.tsx', 'utf-8');
  assert(src.includes('childId && !verifyRes.passToken'), 'Modal must guard against absent passToken');
});

await test('ParentHomeView.onSuccess re-throws when passReference is absent', async () => {
  const { readFileSync } = await import('fs');
  const src = readFileSync('./src/views/ParentHomeView.tsx', 'utf-8');
  assert(src.includes("throw new Error('Pass not ready')"), 'onSuccess must re-throw on missing passReference');
});

await test('verify-action hard-fails when childId provided and parentProfile is null', async () => {
  const { readFileSync } = await import('fs');
  const src = readFileSync('./src/server/routes/auth.ts', 'utf-8');
  assert(src.includes('if (childId) {') && src.includes('if (!req.parentProfile) {'),
    'verify-action must check childId then hard-fail if parentProfile is null');
  assert(!src.includes('if (childId && req.parentProfile) {'),
    'OLD silent-skip pattern must be removed');
});

await test('verify-action self-verifies passToken before returning', async () => {
  const { readFileSync } = await import('fs');
  const src = readFileSync('./src/server/routes/auth.ts', 'utf-8');
  assert(src.includes('isChildPassAuthorized(req.parentProfile.id, childId, passAuth.passToken)'),
    'verify-action must self-verify passToken immediately');
});

// Summary
console.log('\n==============================================');
console.log(`TOTAL: ${passed + failed} | PASSED: ${passed} | FAILED: ${failed}`);
if (failures.length > 0) {
  console.error('\nFailed tests:');
  failures.forEach(f => console.error(`  - ${f}`));
  process.exit(1);
} else {
  console.log('\nAll pass authorization tests PASSED.');
  process.exit(0);
}
