import { api } from '../services/api';

// Helper to convert base64 to Uint8Array for the browser's applicationServerKey
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/\-/g, '+')
    .replace(/_/g, '/');

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export async function subscribeUserToPush(): Promise<{ success: boolean; error?: string }> {
  try {
    if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
      return { success: false, error: 'Push notifications are not supported on this browser.' };
    }

    const registration = await navigator.serviceWorker.ready;
    if (!registration) {
      return { success: false, error: 'Service worker is not active.' };
    }

    // Request permissions first
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      return { success: false, error: 'Notification permission denied.' };
    }

    // Retrieve VAPID Key from the server dynamically
    const { publicKey } = await api.parent.getVapidPublicKey();
    if (!publicKey) {
      return { success: false, error: 'Push notification server key not found.' };
    }

    // Subscribe using the retrieved VAPID Key
    const subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(publicKey)
    });

    // Send subscription object to backend
    const subJson = subscription.toJSON();
    if (!subJson.endpoint || !subJson.keys || !subJson.keys.p256dh || !subJson.keys.auth) {
      return { success: false, error: 'Invalid subscription object generated by the browser.' };
    }

    await api.parent.savePushSubscription({
      endpoint: subJson.endpoint,
      keys: {
        p256dh: subJson.keys.p256dh,
        auth: subJson.keys.auth
      }
    });

    return { success: true };
  } catch (err: any) {
    console.error('Error during push subscription:', err);
    return { success: false, error: err.message || 'Failed to complete subscription.' };
  }
}
